<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="scara_robot">

  <!-- Robot Parameters -->
  <xacro:property name="L1" value="0.228"/>  <!-- Link 1 length: 228mm = 0.228m -->
  <xacro:property name="L2" value="0.1365"/> <!-- Link 2 length: 136.5mm = 0.1365m -->
  <xacro:property name="base_height" value="0.100"/> <!-- Base height: 100mm -->
  <xacro:property name="link_radius" value="0.025"/> <!-- Link radius: 25mm -->
  <xacro:property name="z_max" value="0.150"/> <!-- Z-axis max travel: 150mm -->
  
  <!-- Joint Limits (degrees to radians) -->
  <xacro:property name="j1_min" value="${-90.0 * pi / 180.0}"/>   <!-- -90 deg -->
  <xacro:property name="j1_max" value="${266.0 * pi / 180.0}"/>   <!-- 266 deg -->
  <xacro:property name="j2_min" value="${-150.0 * pi / 180.0}"/>  <!-- -150 deg -->
  <xacro:property name="j2_max" value="${150.0 * pi / 180.0}"/>   <!-- 150 deg -->
  <xacro:property name="j3_min" value="${-162.0 * pi / 180.0}"/>  <!-- -162 deg -->
  <xacro:property name="j3_max" value="${162.0 * pi / 180.0}"/>   <!-- 162 deg -->

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.050" length="${base_height}"/>
      </geometry>
      <material name="base_color">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.050" length="${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint 1 (Base Rotation) -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${j1_min}" upper="${j1_max}" effort="100.0" velocity="2.0"/>
  </joint>

  <!-- Link 1 -->
  <link name="link1">
    <visual>
      <origin xyz="${L1/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${link_radius}" length="${L1}"/>
      </geometry>
      <material name="link1_color">
        <color rgba="0.2 0.2 0.8 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="${L1/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${link_radius}" length="${L1}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="${L1/2} 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint 2 (Shoulder/Elbow) -->
  <joint name="joint2" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="${L1} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${j2_min}" upper="${j2_max}" effort="100.0" velocity="2.0"/>
  </joint>

  <!-- Link 2 -->
  <link name="link2">
    <visual>
      <origin xyz="${L2/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${link_radius}" length="${L2}"/>
      </geometry>
      <material name="link2_color">
        <color rgba="0.8 0.2 0.2 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="${L2/2} 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${link_radius}" length="${L2}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <origin xyz="${L2/2} 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Joint 3 (Wrist Rotation - Phi) -->
  <joint name="joint3" type="revolute">
    <parent link="link2"/>
    <child link="wrist"/>
    <origin xyz="${L2} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${j3_min}" upper="${j3_max}" effort="50.0" velocity="2.0"/>
  </joint>

  <!-- Wrist Link -->
  <link name="wrist">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.015"/>
      </geometry>
      <material name="wrist_color">
        <color rgba="0.2 0.8 0.2 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.015"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <!-- Joint 4 (Z-axis - Prismatic) -->
  <joint name="joint_z" type="prismatic">
    <parent link="wrist"/>
    <child link="end_effector"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="${z_max}" effort="50.0" velocity="0.1"/>
  </joint>

  <!-- End Effector (Gripper) -->
  <link name="end_effector">
    <visual>
      <origin xyz="0 0 -0.02" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.04"/>
      </geometry>
      <material name="end_effector_color">
        <color rgba="0.8 0.8 0.2 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 -0.02" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.04"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 -0.02" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <!-- Gripper Joint (Virtual) -->
  <joint name="gripper_joint" type="prismatic">
    <parent link="end_effector"/>
    <child link="gripper_left"/>
    <origin xyz="0 0.02 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="0.02" effort="10.0" velocity="0.05"/>
  </joint>

  <link name="gripper_left">
    <visual>
      <origin xyz="0 0.01 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.03"/>
      </geometry>
      <material name="gripper_color">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
  </link>

  <joint name="gripper_joint2" type="prismatic">
    <parent link="end_effector"/>
    <child link="gripper_right"/>
    <origin xyz="0 -0.02 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.02" upper="0" effort="10.0" velocity="0.05"/>
  </joint>

  <link name="gripper_right">
    <visual>
      <origin xyz="0 -0.01 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.02 0.03"/>
      </geometry>
      <material name="gripper_color">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
  </link>

  <!-- Gazebo Plugins -->
  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters>$(find scara_description)/config/controllers.yaml</parameters>
    </plugin>
  </gazebo>

</robot>

